module Test
  class Property
    def method_property1: () -> bool
    alias alias method_property1
  end

  class Sleep
    def sleep: () -> bot
  end

  class List[T]
    attr_reader head: T?
    attr_reader tail: self?

    def add: (T) -> self
    def each: () { (T) -> void } -> void
  end

  class CSelf
    def self.meth: () -> self
    def meth: () -> self
    def self.arg: (self) -> void
    def arg: (self) -> void
  end

  class CInstance
    def self.meth: () -> instance
    def meth: () -> instance
    def self.arg: (instance) -> void
    def arg: (instance) -> void
  end

  class CClass
    def self.meth: () -> class
    def meth: () -> class
    def self.arg: (class) -> void
    def arg: (class) -> void
  end

  module MSelf
    def self.meth: () -> self
    def meth: () -> self
    def self.arg: (self) -> void
    def arg: (self) -> void
  end

  module MInstance
    def self.meth: () -> instance
    def meth: () -> instance
    def self.arg: (instance) -> void
    def arg: (instance) -> void
  end

  module MClass
    def self.meth: () -> class
    def meth: () -> class
    def self.arg: (class) -> void
    def arg: (class) -> void
  end

  class CMSelf
    include MSelf
  end

  class CMInstance
    include MInstance
  end

  class CMClass
    include MClass
  end

  interface _Interface
    def lit: () -> :sym
    def void: () -> void
    def selfie: (self) -> self
    def instance: (instance) -> instance
    def klass: (class) -> class
  end

  class Interface
    def i: (_Interface) -> void
  end

  class Bottom
    def b: () -> bot
  end

  class A
  end

  class B
  end

  class C
    def initialize: (a: A, b: B) -> void
                  | (a: A) -> void
                  | (b: Complex) -> void
    def run: () -> Integer
  end

  class Value
    def top: (top) -> void
    def bottom: (bot) -> void
  end

  class Accessibility
    public def public_method: () -> void
    private def private_method: () -> void
  end

  class Meth
    def arg1: (Integer) -> String
    def sym: (Symbol) -> self
  end

  class Nested[T]
    def initialize: (T) -> void
    def nest: (Nested[T]) -> self
  end

  module ValueModule
  end

  module ValueModuleWithBasicObject : BasicObject
  end

  module ValueModuleWithInterface[T] : _Each[T], _ToF
    def each_t: () { (T) -> void } -> void
    def too_f: () -> Float
  end

  class BlockReturnVoid
    def initialize: () { () -> void } -> void
    def call: () -> void
  end

  class BlockReturnLiteral
    def initialize: () { () -> :literal! } -> void
    def call: () -> :literal!
  end

  class SkipIfIncludeUntyped
    def u: () { (untyped) -> untyped } -> void
  end

  class SkipPrefix
    def should_not_skip: () -> :ok
    def should_skip: () -> bot
  end

  class NameErrorLogging
    def missing_method: () -> void
  end

  class TypeErrorIsFail
    def type_error: () -> void
  end

  class TestException < Exception
  end

  class ExceptionWithBot
    def exception: () -> bot
  end

  class Coverage[A]
    def one_line: (Integer, Symbol) -> [Integer, Symbol]
    def two_lines:
      [T] (a: Symbol,
        ?b: Integer?,
          **T) -> void
    def three_lines: () -> (:a |
    :b
                      | :c)

    def block: () { (::Integer x) -> 1 } -> 1
    def all_variables: ((A | A), ?A, *A, A, a: A, ?b: A, **A) { (A) -> A } -> (0 | 1 | 2)
    attr_reader a: A? | Object
    def singleton: () -> singleton(Coverage)
  end

  class BlockArgsCheck
    def different_type: () { (Integer) -> void } -> void
  end

  class Set[A]
    def initialize: [X] () -> void
    def foo: (self) -> 123
    def bar: (self) -> 456
  end
end
