require:
  - rubocop-on-rbs

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Include:
  - 'lib/**/*.rb'
  - 'sig/**/*.rbs'

Lint:
  Enabled: true
Lint/EmptyBlock:
  Enabled: false
Lint/SymbolConversion:
  Enabled: false

Style:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: always
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: true

Metrics:
  Enabled: false

Layout:
  Enabled: true
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Max: 150

Naming:
  Enabled: false
